# Generated by Django 3.1.2 on 2020-10-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_categories_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.categories'),
        ),
        migrations.AddField(
            model_name='images',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.locations'),
        ),
    ]
