# Generated by Django 3.1.2 on 2020-10-14 08:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201010_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_link',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
